### ISSUE TITLE
 works in kitty and xfce terminal under x11 and a possible bug

### ISSUE THREAD

**Issue by emekoi** [mcpcpc/kc#4]
i can confirm that kfc works in kitty and xfce terminal under x11.

on a unrelated note, why does kfc overwrite color number #12 with colors 13-15? [link](https://github.com/mcpcpc/kfc/blob/d563ca9720d7210981d8a7b04098bb0fe9cd9c89/kfc.c#L25-L28). on some terminal emulators like alacritty, this just sets colors 13-15 to lighter versions of colors 5-7, but some other emulators like kitty it just leaves the colors from the original palette.

**Comment by mcpcpc** [comment]
a nice glaring issue. i always thought some of the color schemes looked slightly off... will push a fix + release tarballs in the next day or two. thanks!
