### ISSUE TITLE
dead link in readme

### ISSUE THREAD

**Issue by u20n** [mcpcpc/kc#6]
**Describe the bug**
Thanks for making this wonderful piece of software! I noticed that your ReadMe's reference [1] to kiss linux redirects to a parked domain -- the current url for kiss linux is kisslinux.org.

**Comment by mcpcpc** [comment]
Thank you for your kind words! The dead link is now removed per commit https://github.com/mcpcpc/kfc/commit/d9a2e0367c82e4eb2dc149bead8f8154771a1d7e
